version: '3'
services:
    flask-web:
        build: .
        ports:
            - '${FLASK_PORT}'
        depends_on:
            - redis

    redis:
        image: redis:rc-alpine
        restart: always
        command: redis-server --requirepass '${REDIS_PASSWORD}'
        ports:
            - '${REDIS_PORT}'
        volumes:
            - My-Games:/var/lib/redis

volumes:
    My-Games:
#