version: '3'
services:
    flask-web:
        build: .
        ports:
            - '8777:8777'
        links:
            - 'redis-db:redis'
        depends_on:
            - redis-db
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224

    redis-db:
        image: redis:rc-alpine
        restart: always
        command: redis-server --requirepass wog123
        ports:
            - '6379:6379'
        volumes:
            - My-Games:/var/lib/redis

volumes:
    My-Games: