version: '3'
services:
    flask-web:
        build: .
        ports:
            - '8777:8777'
        depends_on:
            - redis

    redis:
        image: redis:rc-alpine
        restart: always
        command: redis-server --requirepass wog123
        ports:
            - '6379:6379'
        volumes:
            - My-Games:/var/lib/redis

volumes:
    My-Games: